import { createClient } from 'npm:@supabase/supabase-js@2';
import webpush from 'npm:web-push@3.6.7';

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const VAPID_PUBLIC='BB_9JJyvvN72cV8Xg2TsEOWFeS4LRb__Xz8SYJqUrU7p8UjE_CXSXP9OZC10jyLn7EMHs5F_gy-kFrT4PtiE8xM';
const service=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type, x-vccf-cron-secret'}});
const manilaDay=(d=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const manilaTime=(d=new Date())=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);
const manilaWeekday=(d=new Date())=>new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Manila',weekday:'long'}).format(d);
const cleanTime=(v:string|null)=>String(v||'').slice(0,5);

type Caller={kind:'cron'}|{kind:'user',user:any,profile:any};
async function config(){const r=await service.rpc('vccf_push_private_config');if(r.error)throw r.error;const row=Array.isArray(r.data)?r.data[0]:r.data;if(!row?.vapid_private_key||!row?.cron_secret)throw new Error('Push configuration is incomplete.');return row as {vapid_private_key:string;cron_secret:string}}
async function caller(req:Request,cronSecret:string):Promise<Caller|null>{const internal=req.headers.get('x-vccf-cron-secret');if(internal&&internal===cronSecret)return {kind:'cron'};const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return null;const u=await service.auth.getUser(token);if(u.error||!u.data.user)return null;const p=await service.from('profiles').select('user_id,role,member_id,area_id').eq('user_id',u.data.user.id).maybeSingle();if(p.error||!p.data)return null;return {kind:'user',user:u.data.user,profile:p.data}}
async function targetSubscriptions(a:any){const sr=await service.from('push_subscriptions').select('id,user_id,endpoint,p256dh,auth_key').eq('enabled',true);if(sr.error)throw sr.error;const subs=sr.data||[];if(!subs.length)return [];const userIds=[...new Set(subs.map(x=>x.user_id))];const pr=await service.from('profiles').select('user_id,role,member_id,area_id').in('user_id',userIds);if(pr.error)throw pr.error;const profiles=pr.data||[];let allowed=new Set<string>();if(a.audience==='All')allowed=new Set(userIds);else if(a.audience==='Leaders')allowed=new Set(profiles.filter(p=>['admin','pastor','area_leader','ministry_leader'].includes(String(p.role))).map(p=>p.user_id));else if(a.audience==='Area')allowed=new Set(profiles.filter(p=>p.area_id&&p.area_id===a.area_id).map(p=>p.user_id));else if(a.audience==='Ministry'){const memberIds=profiles.map(p=>p.member_id).filter(Boolean);if(memberIds.length){const [mm,lead]=await Promise.all([service.from('member_ministries').select('member_id,ministry_id').eq('ministry_id',a.ministry_id).in('member_id',memberIds),service.from('church_leadership').select('member_id,ministry_id,is_active').eq('ministry_id',a.ministry_id).eq('is_active',true).in('member_id',memberIds)]);if(mm.error)throw mm.error;if(lead.error)throw lead.error;const mids=new Set([...(mm.data||[]).map(x=>x.member_id),...(lead.data||[]).map(x=>x.member_id)]);allowed=new Set(profiles.filter(p=>p.member_id&&mids.has(p.member_id)).map(p=>p.user_id));}}return subs.filter(s=>allowed.has(s.user_id))}
async function sendRow(table:string,a:any,privateKey:string){const subs=await targetSubscriptions(a);webpush.setVapidDetails('mailto:newgenstudios12@gmail.com',VAPID_PUBLIC,privateKey);const payload=JSON.stringify({title:a.title||'VCCF Connect',body:a.body||'New notification',url:a.push_url||'/',tag:table+'-'+a.id,data:{source_table:table,id:a.id}});let sent=0,failed=0,removed=0;const deliveredUsers=new Set<string>();await Promise.all(subs.map(async s=>{try{await webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth_key}},payload,{TTL:86400});sent++;deliveredUsers.add(s.user_id)}catch(error:any){failed++;const status=Number(error?.statusCode||0);if(status===404||status===410){await service.from('push_subscriptions').delete().eq('id',s.id);removed++}else console.error('push failed',status,error?.message||error)}}));if(deliveredUsers.size){const inboxRows=[...deliveredUsers].map(user_id=>({user_id,title:a.title||'VCCF Connect',body:a.body||'New notification',kind:table==='church_announcements'?'announcement':'push',is_read:false}));const saved=await service.from('vccf_notifications').insert(inboxRows);if(saved.error)console.error('inbox insert failed',saved.error.message)}await service.from(table).update({last_push_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',a.id);return {source:table,id:a.id,sent,failed,removed,inbox:deliveredUsers.size}}
function isDue(a:any,now=new Date()){
  if(!a.is_published||!a.push_enabled)return false;
  if(a.publish_at&&new Date(a.publish_at)>now)return false;
  if(a.expires_at&&new Date(a.expires_at)<=now)return false;
  if(a.recurrence==='daily'){
    if(!a.daily_time)return false;
    const last=a.last_push_at?manilaDay(new Date(a.last_push_at)):null;
    return last!==manilaDay(now)&&cleanTime(a.daily_time)<=manilaTime(now);
  }
  if(a.recurrence==='weekly'){
    if(!a.daily_time||!a.publish_at)return false;
    const scheduledWeekday=manilaWeekday(new Date(a.publish_at));
    if(manilaWeekday(now)!==scheduledWeekday)return false;
    const last=a.last_push_at?manilaDay(new Date(a.last_push_at)):null;
    return last!==manilaDay(now)&&cleanTime(a.daily_time)<=manilaTime(now);
  }
  return !a.last_push_at;
}
function canManualSend(who:Caller,a:any){if(who.kind==='cron')return true;const role=String(who.profile.role||'');if(role==='admin'||role==='pastor')return true;return role==='area_leader'&&a.audience==='Area'&&a.area_id&&a.area_id===who.profile.area_id}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type, x-vccf-cron-secret'}});if(req.method!=='POST')return json({error:'POST required'},405);try{const cfg=await config(),who=await caller(req,cfg.cron_secret);if(!who)return json({error:'Unauthorized'},401);const body=await req.json().catch(()=>({}));if(body.mode==='due'){if(who.kind!=='cron')return json({error:'Scheduled dispatch is internal only.'},403);const [ann,push]=await Promise.all([service.from('church_announcements').select('*').eq('is_published',true).eq('push_enabled',true).order('publish_at',{ascending:true}).limit(500),service.from('push_notifications').select('*').eq('is_published',true).eq('push_enabled',true).order('publish_at',{ascending:true}).limit(500)]);if(ann.error)throw ann.error;if(push.error)throw push.error;const jobs=[...(ann.data||[]).filter(isDue).map(a=>['church_announcements',a] as const),...(push.data||[]).filter(isDue).map(a=>['push_notifications',a] as const)];const results=[];for(const [table,a] of jobs)results.push(await sendRow(table,a,cfg.vapid_private_key));return json({ok:true,due:jobs.length,results})}
const table=body.source==='push'||body.table==='push_notifications'?'push_notifications':'church_announcements';const id=String(body.notification_id||body.announcement_id||'');if(!id)return json({error:'notification_id required'},400);const ar=await service.from(table).select('*').eq('id',id).maybeSingle();if(ar.error||!ar.data)return json({error:'Notification not found'},404);if(!canManualSend(who,ar.data))return json({error:'You do not have permission to push this notification.'},403);if(!ar.data.is_published||!ar.data.push_enabled)return json({error:'Notification is not enabled for push.'},400);return json({ok:true,result:await sendRow(table,ar.data,cfg.vapid_private_key)})}catch(error:any){console.error(error);return json({error:error?.message||String(error)},500)}});
