-- Worship Leader ministry members can read Music Ministry and submit their assigned line-ups.
create policy "worship leaders ministry read" on public.worship_service_schedules
for select to authenticated using (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry')));

create policy "worship leaders ministry read" on public.worship_schedule_assignments
for select to authenticated using (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry')));

create policy "worship leaders ministry read" on public.worship_lineups
for select to authenticated using (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry')));

create policy "worship leaders ministry read" on public.worship_lineup_songs
for select to authenticated using (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry')));

create policy "worship leaders ministry insert" on public.worship_lineups for insert to authenticated with check (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=worship_lineups.schedule_id and lower(trim(wa.ministry_role))='worship leader') and worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid())) and status in ('Draft','Submitted') and approved_by is null and approved_at is null);

create policy "worship leaders ministry update" on public.worship_lineups for update to authenticated using (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=worship_lineups.schedule_id and lower(trim(wa.ministry_role))='worship leader') and worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid()))) with check (exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=worship_lineups.schedule_id and lower(trim(wa.ministry_role))='worship leader') and worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid())) and status in ('Draft','Submitted') and approved_by is null and approved_at is null);

create policy "worship leaders ministry insert" on public.worship_lineup_songs for insert to authenticated  with check (exists (select 1 from public.worship_lineups wl where wl.id=worship_lineup_songs.lineup_id and exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=wl.schedule_id and lower(trim(wa.ministry_role))='worship leader') and wl.worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid())) and wl.status in ('Draft','Submitted')));

create policy "worship leaders ministry update" on public.worship_lineup_songs for update to authenticated using (exists (select 1 from public.worship_lineups wl where wl.id=worship_lineup_songs.lineup_id and exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=wl.schedule_id and lower(trim(wa.ministry_role))='worship leader') and wl.worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid())) and wl.status in ('Draft','Submitted'))) with check (exists (select 1 from public.worship_lineups wl where wl.id=worship_lineup_songs.lineup_id and exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=wl.schedule_id and lower(trim(wa.ministry_role))='worship leader') and wl.worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid())) and wl.status in ('Draft','Submitted')));

create policy "worship leaders ministry delete" on public.worship_lineup_songs for delete to authenticated using (exists (select 1 from public.worship_lineups wl where wl.id=worship_lineup_songs.lineup_id and exists (select 1 from public.profiles p join public.member_ministries mm on mm.member_id=p.member_id join public.ministries mn on mn.id=mm.ministry_id join public.worship_schedule_assignments wa on wa.member_id=p.member_id where p.user_id=(select auth.uid()) and lower(trim(mn.name)) in ('worship leader','worship leaders','worship leader ministry','worship leaders ministry') and wa.schedule_id=wl.schedule_id and lower(trim(wa.ministry_role))='worship leader') and wl.worship_leader_member_id in (select member_id from public.profiles where user_id=(select auth.uid())) and wl.status in ('Draft','Submitted'))) ;
